name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      # Optional: Print project ID for debugging
      - name: Echo project ID
        run: |
          echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"

      # Task 1: Configure Docker for Artifact Registry
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          # TODO: Configure Docker for Artifact Registry

      # Task 2: Build and push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-service:latest
          docker build -t $IMAGE .
          docker push $IMAGE
          # TODO: Build Docker image and push to Artifact Registry

      # Task 3: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          IMAGE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-service:latest
          gcloud run deploy my-service \
            --image $IMAGE \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}
          # TODO: Deploy image to Cloud Run using gcloud run deploy
